version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cms_create
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - cms_network
      

  app:
    build: .
    container_name: cms_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cms_create?useSSL=false&serverTimezone=UTC&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    networks:
      - cms_network

networks:
  cms_network:

volumes:
  mysql_data:
